---
title: Configure Crash Control
description: Configure general settings for crash control
privilege: TrustedInstaller
actions:

    # === (AutoReboot) Allow Windows to automatically restart after a system crash - Disabled
    # ------> https://admx.help/?Category=security-compliance-toolkit&Policy=Microsoft.Policies.MSS::Pol_MSS_AutoReboot
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\CrashControl', value: 'AutoReboot', type: REG_DWORD, data: '0'}
    # === Generate Crash Dumps - Enabled
    # ------> Configured to drop a -> Small memory dump (64KB)
    # ------> https://support.microsoft.com/en-us/help/254649/overview-of-memory-dump-file-options-for-windows
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\CrashControl', value: 'CrashDumpEnabled', type: REG_DWORD, data: '3'}
