---
title: Packages
description: Removes system (WinSxS) packages
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: "Removing system packages"}
  - !run:
    path: "%ProgramFiles(x86)%\\Revision Tool"
    exe: "revitool.exe"
    args: "winpackage --install system-components-removal"
    wait: true
    runas: currentUserElevated
    weight: 100

  - !writeStatus: {status: 'Disabling Windows Defender', option: 'disable-defender'}
  - !run:
    path: "%ProgramFiles(x86)%\\Revision Tool"
    exe: "revitool.exe"
    args: "defender disable"
    wait: true
    runas: currentUserElevated
    weight: 100
    option: 'disable-defender'

  - !writeStatus: {status: 'Enabling Windows Defender', option: 'enable-defender'}
  - !run:
    path: "%ProgramFiles(x86)%\\Revision Tool"
    exe: "revitool.exe"
    args: "defender enable"
    wait: true
    runas: currentUserElevated
    weight: 100
    option: 'enable-defender'


# NOTE: This method of removing system packages is now deprecated and not recommended by Revision, as it is one of the main cause of #49

#   - !systemPackage: {name: 'Microsoft-Windows-AcProxy', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-CEIPEnable-Adm', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Client-SQM-Consolidator', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-SQM-Consolidator-Base', arch: amd64, language: 'neutral'}
# #    sqmapi dll is present in Revision, which this would remove
# #  - !systemPackage: {name: 'Microsoft-Windows-SQMApi', arch: amd64, language: 'neutral'}
# #  - !systemPackage: {name: 'Microsoft-Windows-SQMApi', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-UsbCeip', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-UsbCeip', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-OOBE-FirstLogonAnimExe', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-OOBE-FirstLogonAnim', arch: amd64, language: 'neutral'}
#   #   Breaks compatibility with older games #3
#   # - !systemPackage: {name: 'Microsoft-Windows-GameExplorer', arch: amd64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-GameExplorer', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Indeo4-Codecs', arch: x86, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Indeo5-Codecs', arch: x86, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-OneDrive-Setup-Deployment-LanguagePack', arch: amd64, language: 'en-US', option: "remove-onedrive"}
#   - !systemPackage: {name: 'Microsoft-Windows-OneDrive-Setup-Deployment', arch: amd64, language: 'neutral', option: "remove-onedrive"}
#   - !systemPackage: {name: 'Microsoft-Windows-OneDrive-Setup-WOW64-Deployment-LanguagePack', arch: amd64, language: 'en-US', option: "remove-onedrive"}
#   - !systemPackage: {name: 'Microsoft-Windows-OneDrive-Setup-WOW64-Deployment', arch: amd64, language: 'neutral', option: "remove-onedrive"}
#   - !systemPackage: {name: 'Microsoft-Windows-SystemSettings-SettingsHandlers-OneDriveBackup', arch: amd64, language: 'neutral', option: "remove-onedrive"}
#   - !systemPackage: {name: 'Microsoft-Windows-PhotoBasic-Feature-WOW64-Deployment-LanguagePack', arch: amd64, language: 'en-US'}
#   - !systemPackage: {name: 'Microsoft-Windows-PhotoBasic-Feature-WOW64-Deployment', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-PhotoBasic-PictureTools-WOW64-Deployment-LanguagePack', arch: amd64, language: 'en-US'}
#   - !systemPackage: {name: 'Microsoft-Windows-PhotoBasic-PictureTools-WOW64-Deployment', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-PhotoBasic-WOW64-merged-Deployment-LanguagePack', arch: amd64, language: 'en-US'}
#   - !systemPackage: {name: 'Microsoft-Windows-PhotoBasic-WOW64-merged-Deployment', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-shimgvw', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-RetailDemo-RetailInfo', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-RetailDemo-Service.Deployment', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-RetailDemo-Service.Instrumentation', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-RetailDemo-Service', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Shell-RetailDemo-DesktopTaskFactory', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Bubbles', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Mystify', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-PhotoScreensaver', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Ribbons', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-scrnsave', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-scrnsave', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-ssText3d', arch: amd64, language: 'neutral'}
#   #   Stripping Security Center introduces compatibility issues with Defender, it is disabled instead
#   # - !systemPackage: {name: 'Microsoft-Windows-Securitycenter-Adm', arch: amd64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-SecurityCenter-Broker', arch: amd64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-SecurityCenter-Broker', arch: wow64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-SecurityCenter-ControlPanel', arch: amd64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-SecurityCenter-ControlPanel', arch: wow64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-SecurityCenter-Core', arch: amd64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-SecurityCenter-Core', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Skype-ORTC', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Skype-ORTC', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Shell-SoundThemes', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Services-TargetedContent', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-OneCore-SystemSettings-InputCloudStore', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Application-Experience-AIT-Static', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Application-Experience-AppInv', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Application-Experience-Core-Inventory-Service', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Application-Experience-Inventory-Data-Sources', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Application-Experience-Mitigations-C8', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Application-Experience-Program-Data', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Compat-Appraiser-InboxDataFiles', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Compat-Appraiser-Logger', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Compat-Appraiser', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Compat-CompatTelRunner', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Compat-GeneralTel', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-CoreSystem-Bluetooth-Telemetry', arch: amd64, language: 'neutral', regexExcludeFiles: ['.*\\BthTelemetry.dll']}
#   - !systemPackage: {name: 'Microsoft-Windows-CoreSystem-Bluetooth-Telemetry', arch: wow64, language: 'neutral', regexExcludeFiles: ['.*\\BthTelemetry.dll']}
#   - !systemPackage: {name: 'Microsoft-Windows-DataCollection-Adm', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-DeviceCensus-Schedule-ClientServer', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-KeyboardDiagnostic', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Power-EnergyEstimationEngine-Client-Overrides', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-SetupPlatform-Telemetry-AutoLogger', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-SystemSettings-SettingsHandlers-SIUF', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-TelemetryClient', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-TelemetryClient', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Unified-Telemetry-Client-Aggregators', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Unified-Telemetry-Client-AutoLogger-Default', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Unified-Telemetry-Client-Decoder-Host', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Unified-Telemetry-Client-Settings-WindowsClient', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Unified-Telemetry-Client-WoWOnly', arch: wow64, language: 'neutral', regexExcludeFiles: ['.*\\utcapi.dll', '.*\\utcutil.dll']}
#   - !systemPackage: {name: 'Microsoft-Windows-Unified-Telemetry-Client', arch: amd64, language: 'neutral', regexExcludeFiles: ['.*\\utcapi.dll', '.*\\utcutil.dll']}
#   - !systemPackage: {name: 'Microsoft-Windows-Update-Aggregators', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Windows-System-Diagnostics-Telemetry-PlatformTelemetryClient', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-UNP-Task', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-UNP', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-OneCoreUAP-Feedback-StringFeedbackEngine', arch: amd64, language: 'neutral'}
#   #  Caused automatic repair loop
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReporting-Adm-Deployment-LanguagePack', arch: amd64, language: 'en-US'}
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReporting-Adm-Deployment', arch: amd64, language: 'neutral'}
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingCompatibility', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingCompatibility', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingConsole', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingCore', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingDumpTypeControl-Deployment', arch: amd64, language: 'neutral'}
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingFaults', arch: amd64, language: 'neutral'}
#   #   Breaks compatibility with some games, https://github.com/Atlas-OS/Atlas/issues/685  
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingFaults', arch: wow64, language: 'neutral'}
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingKernel', arch: amd64, language: 'neutral'}
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingPowershell', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingPowershell', arch: wow64, language: 'neutral'}
# #  - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingUI', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-ErrorReportingUI', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Feedback-CourtesyEngine', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Feedback-DeploymentMgrClient-Desktop-TaskSch', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Feedback-DeploymentMgrClient', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Feedback-Service', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-FeedbackNotifications-Adm', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-BuildFlighting', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Flighting-FeatureConfiguration-Tasks', arch: amd64, language: 'neutral'}
# #   Causes winver to show 2009, and makes start menu use the old block icon type
# # - !systemPackage: {name: 'Microsoft-Windows-Flighting-FeatureConfiguration', arch: amd64, language: 'neutral'}
# # - !systemPackage: {name: 'Microsoft-Windows-Flighting-FeatureConfiguration', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-Flighting-Settings', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-SystemSettings-SettingsHandlers-Flights', arch: amd64, language: 'neutral'}
#   # Breaks benchmarking tools like Passmark
#   # - !systemPackage: {name: 'Microsoft-Windows-Data-Pdf.Events', arch: amd64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-Data-Pdf.Events', arch: wow64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-Data-Pdf', arch: amd64, language: 'neutral'}
#   # - !systemPackage: {name: 'Microsoft-Windows-Data-Pdf', arch: wow64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-PortableWorkspaces-SSO', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-PortableWorkspaces-SysPrep', arch: amd64, language: 'neutral'}
#   - !systemPackage: {name: 'Microsoft-Windows-PortableWorkspaces-SysPrep', arch: wow64, language: 'neutral'}
