---
title: Configure Updates -> Drivers
description: Configure Windows Update settings for device drivers
privilege: TrustedInstaller
actions:

 - !run:
    path: "%ProgramFiles%\\Revision Tool"
    exe: "revitool.exe"
    args: "tweaks updates wu-drivers disable"
    wait: true
    runas: currentUserElevated